FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY server.js ./
COPY package.json ./
RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup
USER appuser
EXPOSE 3000
ENTRYPOINT ["node"]
CMD ["server.js", "development"]
